/**
 * \mainpage Documentação da IDL
 */
#ifndef CORE_IDL
#define CORE_IDL

/**
 * \brief Módulo principal
 */
module openbusidl {
    /** \brief Representa um identificador universalmente único. */
    typedef string UUID;
    /** \brief Representa um identificador único. */
    typedef UUID Identifier;
};

#endif
