/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_IDL__
#define __TECGRAF_OPENBUS_CORE_IDL__

/**
 * \brief Módulo dos sistemas e aplicações do Tecgraf.
 */
module tecgraf {

/**
 * \brief Módulo do \e middleware OpenBus.
 */
module openbus {

/**
 * \brief Módulo dos <b> Serviços Básicos </b> do OpenBus.
 */
module core {

/**
 * \brief Módulo de versionamento dos Serviços Básicos do OpenBus.
 */
module v2_00 {

const octet MajorVersion = 2;
const octet MinorVersion = 0;
const string BusEntity = "OpenBus";
const string BusObjectKey = "OpenBus";
const unsigned short HashValueSize = 32;
const unsigned short EncryptedBlockSize = 256;

/** \brief Representa um identificador único. */
typedef string Identifier;
typedef sequence<Identifier> IdentifierSeq;

typedef octet HashValue[HashValueSize];
typedef octet EncryptedBlock[EncryptedBlockSize];

/** \brief Representa uma sequência de bytes. */
typedef sequence<octet> OctetSeq;

module services {
	
	/** \brief Exceção que sinaliza uma falha interna num serviço básico. */
	exception ServiceFailure { string message; };
	
};

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
