/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_CREDENTIAL_IDL__
#define __TECGRAF_OPENBUS_CORE_CREDENTIAL_IDL__

/**
 * \brief Módulo dos sistemas e aplicações do Tecgraf.
 */
module tecgraf {

/**
 * \brief Módulo do \e middleware OpenBus.
 */
module openbus {

/**
 * \brief Módulo de definições básicos do OpenBus.
 */
module core {

/**
 * \brief Módulo de versionamento dos Serviços Básicos do OpenBus.
 */
module v2_00 {

/**
 * \brief Módulo com definições de credenciais usadas para autenticação.
 */
module credential {

	typedef octet CredentialVersion[2];
	typedef octet CredentialHash[32];
	typedef octet EncryptedBlock[256];
	
	struct CredentialData {
		Identifier bus; // bus UUID
		Identifier login; // caller UUID
		unsigned long ticket; // monotonically increasing counter
		CredentialHash hash; // SHA-2 hash of: 16-byte random + CredentialVersion + ticket + request_id + object_key + operation_name
	};
	
	struct CredentialChain {
		EncryptedBlock signature; // encrypted signature of the SHA-2 hash of 'chainEnc'
		OctetSeq encoded; // encoded call chain data
	};
	
	struct CredentialReset {
		Identifier login; // callee UUID
		EncryptedBlock challenge; // encrypted 16-byte random value
	};
	
}; // credentials

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
