/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_CREDENTIAL_IDL__
#define __TECGRAF_OPENBUS_CORE_CREDENTIAL_IDL__

#include "access_control.idl"

/**
 * \brief Módulo dos sistemas e aplicações do Tecgraf.
 */
module tecgraf {

/**
 * \brief Módulo do \e middleware OpenBus.
 */
module openbus {

/**
 * \brief Módulo de definições básicos do OpenBus.
 */
module core {

/**
 * \brief Módulo de versionamento dos Serviços Básicos do OpenBus.
 */
module v2_00 {

  /**
 * \brief Módulo com definições de credenciais usadas para autenticação.
 */
module credential {
  
  const unsigned long CredentialContextId = 0x42555300; // 1112888064 "BUS\0"
  
  struct CredentialData {
    Identifier bus; // bus UUID
    Identifier login; // caller UUID
    unsigned long session; // session ID
    unsigned long ticket; // monotonically increasing counter
    HashValue hash; // SHA-2 hash of: 16-byte random + CredentialVersion + ticket + request_id + object_key + operation_name
    services::access_control::SignedCallChain chain;
  };
  
  struct CredentialReset {
    Identifier login; // callee UUID
    unsigned long session; // session ID
    EncryptedBlock challenge; // encrypted 16-byte random value
  };
  
}; // credentials

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
