/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_CREDENTIAL_IDL__
#define __TECGRAF_OPENBUS_CORE_CREDENTIAL_IDL__

/**
 * \brief Módulo dos sistemas e aplicações do Tecgraf.
 */
module tecgraf {

/**
 * \brief Módulo do \e middleware OpenBus.
 */
module openbus {

/**
 * \brief Módulo de definições básicos do OpenBus.
 */
module core {

/**
 * \brief Módulo de versionamento dos Serviços Básicos do OpenBus.
 */
module v2_00 {

module credential {
	
	typedef short[2] CredentialVersion;
	typedef octet[32] CredentialHash;
	typedef octet[16] CredentialSessionSecret;
	
	struct CallerCredential {
		Identifier login; // UUID
		long ticket;
		CredentialHash hash; // SHA-2 hash of: 16-byte random + CredentialVersion + ticket + request_id + object_key + operation_name
		sequence<octet> callChain; // encrypted call chain credential
	};
	
	struct CredentialRequest {
		Identifier login; // UUID
		CredentialSessionSecret secret; // encrypted 16-byte random value
	};
	
}

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
